// <auto-generated />
using System;
using Asp_InnerJoin.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp_InnerJoin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250220135249_Primera Migracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asp_InnerJoin.Models.ProductoEntity", b =>
                {
                    b.Property<int>("ID_PRODUCTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PRODUCTO"));

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("int");

                    b.Property<DateTime>("PROD_FECHA_CREACION")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PROD_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PROD_PRECIO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_PRODUCTO");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Asp_InnerJoin.Models.RolEntity", b =>
                {
                    b.Property<int>("ID_ROL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ROL"));

                    b.Property<string>("ROL_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_ROL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Asp_InnerJoin.Models.UsuarioEntity", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<int>("ID_ROL")
                        .HasColumnType("int");

                    b.Property<string>("USU_EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("USU_FECHA_REGISTRO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("USU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_USUARIO");

                    b.HasIndex("ID_ROL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Asp_InnerJoin.Models.ProductoEntity", b =>
                {
                    b.HasOne("Asp_InnerJoin.Models.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Asp_InnerJoin.Models.UsuarioEntity", b =>
                {
                    b.HasOne("Asp_InnerJoin.Models.RolEntity", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("ID_ROL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Asp_InnerJoin.Models.RolEntity", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
